// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUGh6i2S5DBiG1DmgCKGbLgrFJRyrqMjs',
    appId: '1:963244636:web:5e714ab18eb85b6bf9ec99',
    messagingSenderId: '963244636',
    projectId: 'wisata-nusantara-2ab08',
    authDomain: 'wisata-nusantara-2ab08.firebaseapp.com',
    storageBucket: 'wisata-nusantara-2ab08.appspot.com',
    measurementId: 'G-4NJJM7887D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgYhaAbw3ojwvBiRsjSWrlIQEYldnvK04',
    appId: '1:963244636:android:fe2894aef58b5d8ff9ec99',
    messagingSenderId: '963244636',
    projectId: 'wisata-nusantara-2ab08',
    storageBucket: 'wisata-nusantara-2ab08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_wk2Ds5y24JmVSz5Jo3XVeHtFIgtTi7M',
    appId: '1:963244636:ios:9f821bbcbf91f0dcf9ec99',
    messagingSenderId: '963244636',
    projectId: 'wisata-nusantara-2ab08',
    storageBucket: 'wisata-nusantara-2ab08.appspot.com',
    iosClientId: '963244636-1hhgu558f8sg1gat18mkb1j1futs3ri4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wisataNusantaraMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_wk2Ds5y24JmVSz5Jo3XVeHtFIgtTi7M',
    appId: '1:963244636:ios:9f821bbcbf91f0dcf9ec99',
    messagingSenderId: '963244636',
    projectId: 'wisata-nusantara-2ab08',
    storageBucket: 'wisata-nusantara-2ab08.appspot.com',
    iosClientId: '963244636-1hhgu558f8sg1gat18mkb1j1futs3ri4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wisataNusantaraMobile',
  );
}
